picblog/urls.py
from django.contrib import admin
from django.urls import path
import authentication.views
import blog.views 
from django.conf import settings
from django.conf.urls.static import static
from authentication import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('login', authentication.views.login_page, name='login'),
    path('logout/', authentication.views.logout_user, name='logout'),
    path('home/', blog.views.home, name='home'),
    path('signup/', authentication.views.signup_page, name='signup'),
    path('profile/', views.profile, name='profile'),
    path('photo/upload/', blog.views.photo_upload, name='photo_upload'),
    path('upload-profile-photo/', views.upload_profile_photo, name='upload_profile_photo'),
    path('blog/create', blog.views.blog_and_photo_upload, name='blog_create'),
    path('blog/<int:blog_id>', blog.views.view_blog, name='view_blog'),
    path('blog/<int:blog_id>/edit', blog.views.edit_blog, name='edit_blog'),
    path('photo/upload-multiple/', blog.views.create_multiple_photos, name='create_multiple_photos'),
    path('follow-users/', blog.views.follow_users, name='follow_users')
]


if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


    

blog/models.py
from django.conf import settings
from django.db import models
from PIL import Image


class Photo(models.Model):
    image = models.ImageField()
    IMAGE_MAX_SIZE = (800, 800)
    caption = models.CharField(max_length=128, blank=True)
    uploader = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    date_created = models.DateTimeField(auto_now_add=True)


    def resize_image(self):

        image = Image.open(self.image.path)
        image.thumbnail(self.IMAGE_MAX_SIZE)
        image.save(self.image.path)   

    def save(self, *args, **kwargs):

        super().save(*args, **kwargs)
        self.resize_image()   

class BlogContributor(models.Model):
    blog = models.ForeignKey('Blog', on_delete=models.CASCADE)
    contributor = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    contributions = models.CharField(max_length=255, blank=True)

    class Meta:
        unique_together = ('blog', 'contributor')


class Blog(models.Model):
    photo = models.ForeignKey(Photo, null=True, on_delete=models.SET_NULL, blank=True)
    title = models.CharField(max_length=128)
    content = models.CharField(max_length=5000)
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, null=True)
    contributors = models.ManyToManyField(settings.AUTH_USER_MODEL, through='BlogContributor', related_name='contributions')
    date_created = models.DateTimeField(auto_now_add=True)
    starred = models.BooleanField(default=False)
class Meta:
     permissions = [
            ('change_blog_title', 'Peut changer le titre d’un billet de blog')
        ]

templates/base.html
<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <title>FotoBlog</title>
    <!-- CSS global -->
    {% load static %}
    <link rel="stylesheet" href="{% static 'blog/create.css' %}">
</head>
<body>
    <div class="sidebar">
        <h1>FotoBlog</h1>

        {% if user.is_authenticated %}
            <p>Salut, {{ request.user }} !</p>

           {% if user.userprofile.photo %}
           <img id="profile-banner" src="{{ user.userprofile.profile.url }}" alt="Photo de profil">
          {% else %}
        <img id="profile-banner" src="{% static 'blog/photo.jpg' %}" alt="Photo par défaut">
        {% endif %}

            <ul>
                <li><a href="{% url 'home' %}">Accueil</a></li>
                <li><a href="{% url 'profile' %}">Profil</a></li>
                <li><a href="{% url 'blog_create' %}">Écrire un billet</a></li>
                <li><a href="{% url 'upload_profile_photo' %}">Changer la photo de profil</a></li>
                <li><a href="{% url 'follow_users' %}">Suivre des utilisateurs</a></li>
                <li><a href="{% url 'create_multiple_photos' %}">Télécharger plusieurs photos</a></li>
                {% if perms.blog.add_photo %}
                    <li><a href="{% url 'photo_upload' %}">Télécharger une photo</a></li>
                {% endif %}
                <li><a href="{% url 'logout' %}">Se déconnecter</a></li>
            </ul>
        {% endif %}
    </div>

    <div class="main-content">
        {% block content %}
        {% endblock content %}
    </div>
</body>
</html>